### PR TITLE
Fix #83 again (now with tests)

### LINKED ISSUE #83: Cache proxy only supports "new" `GetItems` signature
The crate expects `a((so)(so)(so)iiassusau)` as signature. But at least at-spi2-core is still exporting the old version of `a((so)(so)(so)a(so)assusau)` (probably for compatibility): https://gitlab.gnome.org/GNOME/at-spi2-core/-/blob/b10fcf21b1ef49dd3d6297ac657434ece3b23578/registryd/registry.c#L864-876

Reference to comment that explains the history: https://gitlab.gnome.org/GNOME/at-spi2-core/-/blob/6364851c4b92ab4ed3a3abb0af654f7a5dc9c519/xml/Cache.xml#L72-78

So probably both versions should be supported.

Reproducer:
```rs
use std::error::Error;

use atspi::{cache::CacheProxy, zbus::zvariant::ObjectPath};

#[tokio::main]
async fn main() -> Result<(), Box<dyn Error>> {
    let atspi = atspi::AccessibilityConnection::open().await?;
    let cache = CacheProxy::builder(atspi.connection())
        .destination(atspi.destination())?
        .path(ObjectPath::from_static_str("/org/a11y/atspi/cache")?)?
        .build()
        .await?;
    let items = cache.get_items().await?;
    dbg!(items);
    Ok(())
}
```

Error:
```
Error: Variant(SignatureMismatch(Signature("a((so)(so)(so)a(so)assusau)"), "`a((so)(so)(so)iiassusau)`"))
```

### PR DESCRIPTION
**Pull request by TTWNO**
…rsion functions, and tests

### CODE REVIEW

File: atspi-common/src/events/mod.rs [hunk 1]
```diff
@@ -542,6 +584,11 @@ impl TryFrom<&zbus::Message> for Event {
 				let ev = AddAccessibleEvent::try_from(msg)?;
 				Ok(Event::Cache(CacheEvents::Add(ev)))
 			}
+			// LegacyCacheAdd signature
+			"((so)(so)(so)a(so)assusau)" => {
```
Comment (luukvanderduim) [inline atspi-common/src/events/mod.rs:588]: If you look at the top of this `TryFrom<Message> for Event` impl, you will see we are comparing to a 'Marshalled' signature, because that is what `body_signature()` returns. It has no outer parentheses, typically one pair less than our unmarshalled / Rust type ``Type::Signature()` ones.
In other words, I think we do not want the outer parentheses here, also goes for the other signatures here.

File: atspi-common/src/events/mod.rs [hunk 2]
```diff
@@ -126,9 +126,51 @@ pub enum Event {
...
+	}
+
+	fn sender(&self) -> UniqueName<'_> {
+		self.item.name.clone().into()
+	}
+	fn path(&self) -> ObjectPath<'_> {
+		self.item.path.clone().into()
+	}
+	fn body(&self) -> Self::Body {
+		(self.node_added.clone(),)
```
Comment (luukvanderduim) [inline atspi-common/src/events/mod.rs:170]: Those outer parentheses are unneeded. No need to compensate for the D-Bus marshalling.

**Review by luukvanderduim — CHANGES_REQUESTED** [review]
Please remove the unneeded parentheses and we are done!

**Review by luukvanderduim — APPROVED** [review]
